### ISSUE TITLE
Latest release not working on Mojave?

### ISSUE THREAD

**Issue by Steffan-Ravn** [vjeantet/alerter#24]
I've downloaded your latest version of alerter, but when a run it under Mojave I get the following errors:

> ./alerter -message "Deploy the canons"
> dyld: lazy symbol binding failed: Symbol not found: _objc_opt_new
>   Referenced from: /Users/stre/Downloads/./alerter (which was built for Mac OS X 10.15)
>   Expected in: /usr/lib/libobjc.A.dylib
> 
> dyld: Symbol not found: _objc_opt_new
>   Referenced from: /Users/stre/Downloads/./alerter (which was built for Mac OS X 10.15)
>   Expected in: /usr/lib/libobjc.A.dylib
> 
> Abort trap: 6

If I download and run v002 everything works as expected.

**Comment by romanvbabenko** [comment]
Same on High Sierra

**Comment by jeremybessard** [comment]
Same on Mojave 10.14.6, v003 works only on Catalina.

**Comment by hwcltjn** [comment]
One more confirmation that v0003 does not work on 10.14.6

**Comment by qharouff** [comment]
Just compiled this for myself, it looks like the latest version was built for macOS 10.15+. Simply changing the Deployment Target in Xcode to 10.12 allows me to run on 10.14.6, haven't tested on older OSs yet. Hopefully @vjeantet would be able to recompile a new version with the Deployment Target adjusted?

**Comment by vjeantet** [comment]
Hello, 
V2 and v3 are the same in term of functionality.

V3 -> Catalina
V2 -> before Catalina

**Comment by mmshivesh** [comment]
The problem seems to be that when installing from `brew`, it pulls the latest release which defaults to V3 and doesn't work prior to Catalina

**Comment by Steffan-Ravn** [comment]
If I download the project and change the deployment target to something prior to Catalina (say for example 10.10) and build, it compiles without problems and so far it works on everything I've tested on.

Could you perhaps lower the deployment target and release a new version? Or does the project contain specific code that doesn't work on older versions than Catalina?

**Comment by mmshivesh** [comment]
Yeah I did that just now and it's working fine. In case the command hangs and doesn't show a notification, looking in the Notifications settings of System Preferences might help

**Comment by gbolivar** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
ssl, @RomansWorks, @kinginconntry, @theWhiteFox, @jbialy, @webknjaz, @mkumawat10, @gdziedzic, @rmikehodges, @lunny, @RhetTbull, @austinjk, @AOrps, @noid23, @kashiwaguma-hiro, @joe07274, @elviskahoro, @busracandan, @ohheyitskartik, @Scriptkiddi
